### ISSUE TITLE
A question about AASigner's index

### ISSUE THREAD

**Issue by fjun99** [eth-infinitism/account-abstraction#127]
in ./src/runop.ts, it says that:

  // index is unique for a wallet (so same owner can have multiple wallets, with different index
  const index = parseInt(process.env.AA_INDEX ?? '0')
  console.log('using account index (AA_INDEX)', index)

But in AASigner.ts, it seems that the index is not effective. 

When I change the value of index, I always get the same test account.

The only place related to index seems to have no effect.

```
    const userOp = await fillAndSign({
      sender: this._wallet!.address,
      initCode,
      nonce: initCode == null ? tx.nonce : this.index,
      callData: execFromEntryPoint.data!,
      callGasLimit: tx.gasLimit,
      maxPriorityFeePerGas,
      maxFeePerGas
    }, this.signer, this.entryPoint)
```

Is this index a feature for the future?

thanks.

**Comment by plusminushalf** [comment]
I think `runOp` is meant for demonstration purposes, while if you see the AA-SDK reference then you can see the use of the index variable - https://github.com/eth-infinitism/bundler/blob/main/packages/sdk/src/SimpleWalletAPI.ts#L73

**Comment by fjun99** [comment]
> I think `runOp` is meant for demonstration purposes, while if you see the AA-SDK reference then you can see the use of the index variable - https://github.com/eth-infinitism/bundler/blob/main/packages/sdk/src/SimpleWalletAPI.ts#L73

Thanks. Got it. 

https://github.com/eth-infinitism/account-abstraction/blob/develop/contracts/samples/SimpleWallet.sol

```
function deployWallet(IEntryPoint entryPoint, address owner, uint salt) public returns (SimpleWallet ret)
{...}
```

Maybe we may use SimpleWalletDeployer here to create the wallet in AASigner too.
