### ISSUE TITLE
Suggestion: SimpleWallet signing and validating using EIP712

### ISSUE THREAD

**Issue by fjun99** [eth-infinitism/account-abstraction#128]
Currently, SimpleWallet & AASigner sign UserOperation using Eth Signed Message. By this way, if a user signs using MetaMask or a wallet app, he signs a hash. 

Maybe we can consider using EIP712  `_signTypedData` to sign: UserOperation data, entrypoint address, chainId.  Thanks.

current signing in AASigner

```ts
  const message = arrayify(getRequestId(op2, entryPoint!.address, chainId))
  return {
    ...op2,
    signature: await signer.signMessage(message)
  }
```

validating in SimpleWallet

```solidity
function _validateSignature(UserOperation calldata userOp, bytes32 requestId, address)
  internal override virtual returns (uint256 deadline) {
    bytes32 hash = requestId.toEthSignedMessageHash();
    require(owner == hash.recover(userOp.signature), "wallet: wrong signature");
    return 0;
}
```

**Comment by drortirosh** [comment]
Think of a UserOperation as a transaction.
A wallet extension (or app) displays the transaction to the user and signs it.

That said, you can create your own wallet and use a different signature scheme.
