### ISSUE TITLE
a draft tutorial for first time developer using this repo

### ISSUE THREAD

**Issue by fjun99** [eth-infinitism/account-abstraction#129]
This is a draft.

## Basic usage for first time developer using this EIP-4337 implementation

There are two main repositories in this EIP-4337 Account Abstraction implementation:

- Account Abstraction contracts: https://github.com/eth-infinitism/account-abstraction/ (this repo)
- Bundler Client: https://github.com/eth-infinitism/bundler

As a first time user of this EIP-4337 implementation, you can run it in two ways locally:

1.  signs and sends UserOperation locally (sends a transaction directly).
2.  signs and sends UserOperation to a bundler. Then the bundler sends a bundle transaction on-chain.

---

### basic usage #1: to run a single UserOperation locally

1. git clone repo `account-abstraction` and install dependencies
2. run hardhat local blockchain at `http://localhost:8545`:
```
yarn hardhat node --no-deploy
```
3. deploy contracts to localhost:
```
yarn hardhat deploy --network localhost
```

result:
```
==entrypoint addr= 0x6b2FA6F0771dc5F1AfF20E021dEb2fb436292A4D
==(pre-deployed) wallet= 0x9Cc58DcaB28F84e25aD83429A2672670CDFb6AE0
==testCounter= 0x99E8aB20ee55322b2c4b4d3D2387690f5d219776
```

4. send UserOperation locally (without Bundler). We will create a new contract wallet account in the first round run.
```bash
DEBUG=TRUE yarn runop --network localhost  //or
DEBUG=TRUE FORCE_DEPLOY=NO yarn runop --network localhost
```

The UserOperation is that a `SimpleWallet` wallet calls `TestCounter.jusemit()`. You will see results such as event and gas information.

- The `runop` script:
  - uses account[0] or mnemonic file for funding and as the tx sender
  - deploys a wallet deployer (if not already there)
  - init a AASigner instance(a signer that wraps account-abstraction used with `SimpleWallet` contract)
  - determines the wallet address, and funds it and pre-deposits for it in EntryPoint
  - (first round) sends a UserOperation (which also creates the wallet, and the wallet signer is the sender)
  - (second round) sends another UserOperation, on this existing wallet

5. you can also use pre-deployed wallet (please edit `src/runop.ts` as follows) and run it again

```ts
const walletAddress = '0x9Cc58DcaB28F84e25aD83429A2672670CDFb6AE0'
await aasigner.connectWalletAddress(walletAddress)
```

6. (optional) run unit test

```
yarn hardhat test --network localhost
```

---

### basic usage #2: to send a single UserOperation using bundler

Continue with the former localhost blockchain and the deployed EntryPoint Contract.

1. git clone repo `bundler` in another directory and install dependencies
2. run pre-process
```
yarn preprocess
```
3. edit `bundler/packages/bundler/localconfig/bundler.config.json`. Set "entryPoint" to the already deployed EntryPoint contract: `0x6b2FA6F0771dc5F1AfF20E021dEb2fb436292A4D`. (we ignore `helper` temporarily.)

```json
{
  "gasFactor": "1",
  "port": "3000",
  "network": "http://localhost:8545",
  "entryPoint": "0x6b2FA6F0771dc5F1AfF20E021dEb2fb436292A4D",
  "beneficiary": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
  "minBalance": "1",
  "mnemonic": "./localconfig/mnemonic.txt",
  "helper": "0x780EcF3a794E9eb2b8C9baA6d8C4Ff36EFba770C"
}
```

4. run bundler at `http://localhost:3000/rpc`
```
yarn bundler
```

5. send UserOperation through bundler. In `account-abstraction` directory, run:

```bash
DEBUG=TRUE AA_URL='http://localhost:3000/rpc' yarn runop --network localhost
```

**Comment by drortirosh** [comment]
Thank you.
As you've noticed, we're not that good at documentation...
Indeed wallet developers should user the "sdk" and "bundler" packages, and not directly this repo.
This is mainly the contracts themselves (and the EIP), while "bundler" contains the off-chain tools.
We're on the process of bringing up a doc site, and might use your text.

**Comment by fjun99** [comment]
I think that wallet developers will need to read and run this repo to better understand how EIP-4337 works and how to use it.

**Comment by yoavw** [comment]
Thanks @fjun99 , I think it's great to help devs who want deeper understanding run this repo and play with it to get a "feel" of how the EIP works.
You're also welcome to contribute more content when the docs site is up (soon).

**Comment by fjun99** [comment]
@yoavw sure, I will contribute.

**Comment by FrankFan** [comment]
I tried to run this repo using your guide @fjun99 , 

but when I executed the command: `DEBUG=TRUE yarn runop --network localhost`,
the terminal showed this error:

![image](https://user-images.githubusercontent.com/1589433/210516963-29c03678-6dc5-4356-b120-4b15bca1d334.png)

why cannot estimate gas ?  

could you please help me solving this issue ?

**Comment by FrankFan** [comment]
![image](https://user-images.githubusercontent.com/1589433/210521889-0f1c17c6-480d-452e-bd0d-e89e6a4d1777.png)

after update some code in `runop.ts`

**Comment by LI-YONG-QI** [comment]
> I tried to run this repo using your guide @fjun99 ,
> 
> but when I executed the command: `DEBUG=TRUE yarn runop --network localhost`, the terminal showed this error:
> 
> ![image](https://user-images.githubusercontent.com/1589433/210516963-29c03678-6dc5-4356-b120-4b15bca1d334.png)
> 
> why cannot estimate gas ?
> 
> could you please help me solving this issue ?

I have same error
How do you fix?
