### ISSUE TITLE
A question about wallet nonce

### ISSUE THREAD

**Issue by fjun99** [eth-infinitism/account-abstraction#131]
It seems that the if a wallet is created in the first call, the nonce is not added.

runop results:

0. 1st run gas used: [ { nonce: 0, gasPaid: 1312317, gasUsed: 1114969, diff: -197348 } ]
1. 2nd run: [ { nonce: 0, gasPaid: 64052, gasUsed: 72445, diff: 8393 } ]
2. 1st run gas used: [ { nonce: 1, gasPaid: 62474, gasUsed: 72457, diff: 9983 } ]
3. 2nd run: [ { nonce: 2, gasPaid: 61124, gasUsed: 72483, diff: 11359 } ]

This logic is implemented in the BaseWallet and SimpleWallet contract

```solidity
//in SimpleWallet
    function _validateAndUpdateNonce(UserOperation calldata userOp) internal override {
        require(_nonce++ == userOp.nonce, "wallet: invalid nonce");
    }

//in BaseWallet
    function validateUserOp(UserOperation calldata userOp, bytes32 requestId, address aggregator, uint256 missingWalletFunds)
...        if (userOp.initCode.length == 0) {
            _validateAndUpdateNonce(userOp);
        }
... }
```

However, the first call (which also created the account beforehand) was executed. I think the nonce should be added. And nonces in the results will be 0, 1, 2, 3.

Not quite sure. Hope you can consider this question. Thanks.

**Comment by drortirosh** [comment]
The nonce in the creation UserOp is ignored - there is no real need for a nonce, since creation can only happen once . 
Previously, we used to use the nonce in the creation UserOp as a "salt" to the wallet's address.
(Now the creation salt is part of the initCode)

**Comment by fjun99** [comment]
Thanks. I think the current design is ok as we told developers that the first one and two nonce are. And developers  know that a contract wallet account may have  4 or 5 useroperations as its nonce is 3.
