### ISSUE TITLE
Forbidden opcodes should be forbidden when `depth > 1` not `> 2`?

### ISSUE THREAD

**Issue by hazim-j** [eth-infinitism/account-abstraction#145]
Minor clarification on this line in the EIP:
https://github.com/eth-infinitism/account-abstraction/blob/b41ba0e9db635d525f6c81c8bba66703ae8d283d/eip/EIPS/eip-4337.md?plain=1#L339

If opcode is called by account or paymaster it would have a depth of 2. So `depth > 2` implies its only forbidden for other contracts being called by account or paymaster.

A depth of 1 is where the `NUMBER` delimiter opcode is being called (i.e the EntryPoint).

**Comment by drortirosh** [comment]
correct. will fix.
