### ISSUE TITLE
[L09] Wallet may not be deployed

### ISSUE THREAD

**Issue by drortirosh** [eth-infinitism/account-abstraction#18]
The _validateWalletPrepayment function of the EntryPoint will attempt to deploy the wallet if the operation specifies an initCode. This will fail if the wallet cannot be deployed, or it does not match the sender address. However, operations without an initCode do not guarantee that the wallet has already been deployed. If not, the validateUserOp call will unexpectedly revert before execution enters the try block (so the FailedOp event will not be triggered).
In practice, this should be identified by the bundler when constructing the batch. Nevertheless, in the interest of predictability, consider ensuring _createSenderIfNeeded always ends with a wallet deployed at the expected address.

**Comment by drortirosh** [comment]
I'm reluctant of add it since:
- as you say, a bundler MUST simulate (and catch) such errors in advance, so there is no real security issue.
- It iis not silently ignored, but causes a revert, which is caught by estimateGas (the only this that is missing is the FailOp to tell which op caused this revert of the batch - but can be determined by simulating the UserOps)
- I consider it a compiler bug that `try addr.func() catch {...}` actually reverts, and future compiler version should resolve it cleanly..

**Comment by yoavw** [comment]
This should be caught by the single-op simulation before reaching estimateGas on an entire batch. But it does break a "promise" we make - that handleOps will never revert without FailedOp.  We need to make sure client developers are aware of the need to simulate ops, but I think the EIP already mandates that.

What bothers me about this one, is that it breaches one line of defense.  The batcher has two lines of defense.  One is the pre-batching single-op simulation (aka 2nd simulation), and the other is the estimateGas simulation of the entire handleOps call.  The former is supposed to block any non-paying transaction without performing extra work on the batch.  The latter ensures that if ops somehow end up affecting each other in the validation stage, the batcher can easily identify and remove the bad op.  By giving up the 2nd line of defense in this case, we may be opening up some vulnerability that we're not identifying right now.

I believe such vulnerability doesn't exist in v1, but when v2 allows paymasters to do more, this could become an issue.  For example, if we make the paymaster validation non-view (as we plan to do), then it could trigger the suicide of some wallet, causing the above to revert in handleOps without a FailedOp.  The batcher won't be able to tell which op to remove.
