### ISSUE TITLE
Error: cannot estimate gas When I run `yarn runop`

### ISSUE THREAD

**Issue by LI-YONG-QI** [eth-infinitism/account-abstraction#238]
Hello everyone!
I try to run `runop.ts` script on localhost, but I got the error message

![image](https://user-images.githubusercontent.com/76777953/224022313-4848d2b2-0a27-43fe-8f5e-d4ef14d18730.png)

I found that the  code caused the error
`const ret = await testCounter.justemit();`

When I update the code to `const ret = await testCounter.connect(etherSigner).justemit();` it work
I guessed this error is related to `aasigner`, because `testCounter` is connect aasigner in `runop` script
When I `console.log(aasigner.address)` is `undefined`

Can someone help me?

**Comment by drortirosh** [comment]
not sure what your entire environment is, since this sample works locally (and on testnets).
Please ask the question on the discord group, as we can't take support calls here.
