### ISSUE TITLE
suprious dragon issue in EntryPoint.sol

### ISSUE THREAD

**Issue by shubhodeep786** [eth-infinitism/account-abstraction#241]
contract code size is 27982 bytes and exceeds 24576 bytes . A limit introduced in Spurious Dragon.

**Comment by drortirosh** [comment]
The contract is 22k long (yes, it is big, but within the limit), and already deploy on [many networks](https://blockscan.com/address/0x0576a174D229E3cFA37253523E645A78A0C91B57)
You must compile it with optimizations.
I suggest to run `yarn deploy` from this project to see.
