### ISSUE TITLE
Gas report for bls account

### ISSUE THREAD

**Issue by Bo-00** [eth-infinitism/account-abstraction#243]
HI dev team！ Have you guys do gas test for bls aggregator？Can you give some number about bls  signature verifying？like gas used for 5 message and 5 account at one time...

**Comment by HUGH-XUUUU** [comment]
@derekchiang

**Comment by Bo-00** [comment]
@drortirosh  hi man ❤️ !  I need  help！

**Comment by drortirosh** [comment]
BLS is not gas efficient: validating a signature is ~300k gas
But you do need to calculate on-chain the aggregated hash, in an algorithm called "pairing", which costs ~80k gas per message.
This means that gas-wise ECDSA is much more efficient (only 3000 gas per ,`ecrecover()` )

BLS is efficient only when cpu gas is very cheap, and "calldata" gas is very expensive, as on L2 networks, like Arbitrum and Optimism.

**Comment by Bo-00** [comment]
@drortirosh Thanks! But I have more confuse.  I think the calldata of handleAggregatedOps is longer than handleOps. Can you give me an example of the bls gas cost less than ECDSA?

**Comment by Bo-00** [comment]
@drortirosh Oh I got it. If bundler user handleAggregatedOps,they will place the signature in UserOperations with "0x" , so the bytes get shorter and calldata gas become fewer. Am i right?
