### ISSUE TITLE
Does it make sense to do a length check here?

### ISSUE THREAD

**Issue by JorgeAtPaladin** [eth-infinitism/account-abstraction#248]
https://github.com/eth-infinitism/account-abstraction/blob/ad7ce4990b3c2fe85b1ab593448e8ff50bd14a15/contracts/samples/SimpleAccount.sol#L121

Hi all, I'm curious whether it might make sense to do a greater than zero check on the length here. Similar to OZ's reference:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol#L233

My intuition is that if length is zero you are potentially accessing new memory at `add(result, 32)`, though this might not be problematic as the length seems to still always be 0 in that case?

Cheers, Marco from Paladin.

**Comment by drortirosh** [comment]
Our only purpose is duplicate the exact error as the original revert.
If the revert data is empty string, then mload(result) would return zero, and thus we revert with an empty string.
