### ISSUE TITLE
Many implement has different execute function interface

### ISSUE THREAD

**Issue by imduchuyyy** [eth-infinitism/account-abstraction#253]
In proposal https://eips.ethereum.org/EIPS/eip-4337, author does not declare interface on execute function, so many organizations
declare with different interface.

User can not sync their contract account with different wallet system.

Should we use ERC-2535 for fix them ?.

**Comment by drortirosh** [comment]
ERC 4337 attempt to define the strict minimum on a wallet. Do we suggest (in a sample contract) "execute" and "executeBatch" methods.
Each wallet can have its separate exec method, but it is best to standardize it, in a separate ERC, so that wallets can use different account contracts
