### ISSUE TITLE
Why there are no events for Deposit Paymaster?

### ISSUE THREAD

**Issue by heypran** [eth-infinitism/account-abstraction#256]
I am not sure why there are no events being emitted for operations such as `addTokens`, `unlockTokenDeposit`, `lockTokenDeposit` etc. For some its fine but for some operations such as `addTokens` I think its necessary.

**Comment by UnsignedInt8** [comment]
That's just a sample, you can rewrite a super deposit paymaster for yourself.

**Comment by heypran** [comment]
Yeah I got your point, but I was thinking if there is a standard for this then it would much easier to build tooling and more interactions with other contracts on top of this. What do you think?

**Comment by drortirosh** [comment]
you're right, but we're actually about to deprecate this paymaster, as it is not of much use anyway, so we don't both updating it.

**Comment by peter-jim** [comment]
@heypran hello，I tried to use bunlder signature to interact with paymaster, but the contract verification signature never worked. I would like to ask you whether you have successfully realized the interaction with paymaster. Can you tell me how
