### ISSUE TITLE
Comment on `execute` sample function is misleading

### ISSUE THREAD

**Issue by ebaizel** [eth-infinitism/account-abstraction#258]
In the [SimpleAccount.sol](https://github.com/eth-infinitism/account-abstraction/blob/6dea6d8752f64914dd95d932f673ba0f9ff8e144/contracts/samples/SimpleAccount.sol#L60) example, the comment for the `execute` function mentions this should only be called by the `owner`, not the `EntryPoint`. However, the function checks `_requireFromEntryPointOrOwner()`, which would allow the EntryPoint to call this.

**Comment by drortirosh** [comment]
you're right. the comment says "not entry point" instead of "or entrypoint"
