### ISSUE TITLE
[N04] ECDSA signature length check allows invalid values

### ISSUE THREAD

**Issue by drortirosh** [eth-infinitism/account-abstraction#26]
In the VerifyingPaymaster contract, the validatePaymasterUserOp function contains a check that the ECDSA signature being verified has a length >= 65 bytes. The tryRecover function in the OpenZeppelin ECDSA library does not support signatures longer than 65 bytes. It's possible for an invalid signature length to pass the check in validatePaymasterUserOp and later cause the transaction to revert.
Consider modifying the check in validatePaymasterUserOp to only allow ECDSA signature lengths equal to 65.

**Comment by PranavGarg01** [comment]
> It's possible for an invalid signature length to pass the check in validatePaymasterUserOp and later cause the transaction to revert.

The signature with invalid length will never pass the check as it will always revert in the ECDSA library.
