### ISSUE TITLE
What would cause "AA23 reverted (or OOG)" during `validateUserOp` with a SimpleAccount?

### ISSUE THREAD

**Issue by ebaizel** [eth-infinitism/account-abstraction#263]
I've implemented a wallet nearly identical to SimpleAccount.sol. I'm using a Paymaster from stackup.sh (I'm on the paid plan), and am able to receive paymasterData, and attach that and a signature to the UserOperation.

When I send it to the bundler, I get the error `AA23 reverted (or OOG)`. Looking through the [related code path](https://github.com/eth-infinitism/account-abstraction/blob/v0.4.0/contracts/core/EntryPoint.sol#L352), the only logic that gets run is `validateSignature`. Because there is a paymaster, and I am sending `initCode`, there is no other logic branches that get invoked. Again, this is all in the sample account.

Any ideas why this may be happening? Any guidance on how I could debug this further?

**Comment by drortirosh** [comment]
the validation function reverted without a "revert reason". check if the gas limit is high enough.
Alternately, you can try to use "tenderly" debugger to find the cause
