### ISSUE TITLE
Deployed contracts no longer compatible with eth-infinitism and stackup-wallet bundlers

### ISSUE THREAD

**Issue by d-smith** [eth-infinitism/account-abstraction#266]
Downloading the [latest commit](https://github.com/eth-infinitism/account-abstraction/commit/9b5f2e4bb30a81aa30761749d9e2e43fee64c768) results in Invalid UserOp signature or paymaster signature errors when running [stackup-wallet/erc-4337-examples](https://github.com/stackup-wallet/erc-4337-examples) eth transfer sample with no paymaster.

This problem is not exhibited when checking out and deploying from commit 556f03fadcaba0d7d04cd901e6eb9601db50a998 

I see the error with both the [eth-infinitism](https://github.com/eth-infinitism/bundler) and [stackup-wallet](https://github.com/stackup-wallet/stackup-bundler) bundlers.

**Comment by hazim-j** [comment]
Hi @d-smith, We'll be pushing an update to both stackup-bundler and the erc-4337-examples repo this week to support the latest EntryPoint. These updates should fix your errors.
