### ISSUE TITLE
Sanity check should be updated to account for networks without basefee opcode.

### ISSUE THREAD

**Issue by hazim-j** [eth-infinitism/account-abstraction#271]
Referring to this line in the EIP:

> The maxFeePerGas and maxPriorityFeePerGas are above a configurable minimum value that the client is willing to accept. At the minimum, they are sufficiently high to be included with the current block.basefee.

Some networks don't support the `BASEFEE` opcode. The EntryPoint is aware of this and falls back to legacy mode if `maxFeePerGas` == `maxPriorityFeePerGas`. Should the sanity check be updated to validate this rather than let it fail during simulation?

Something like this should be sufficient:

> ValidateFeePerGas checks the maxFeePerGas is sufficiently high to be included with the current block.basefee. Alternatively, if basefee is not supported, then check that maxPriorityFeePerGas is equal to maxFeePerGas as a fallback.

**Comment by drortirosh** [comment]
You're probably right, but should we need to spec that? We try to spec out things that will break the network if there are inconsistent implementations between bundlers.
However, `basefee` implementation is very consistent for a given network.
