### ISSUE TITLE
Implementing ERC725X interface for account abstraction

### ISSUE THREAD

**Issue by imduchuyyy** [eth-infinitism/account-abstraction#273]
I am currently working with the [eth-infinitism/account-abstraction](https://github.com/eth-infinitism/account-abstraction) repository and attempting to implement the ERC725X interface to enable support for multiple wallet application implementations.

**Comment by imduchuyyy** [comment]
following this link: https://eips.ethereum.org/EIPS/eip-725#erc725x-methods

**Comment by web3-engineer** [comment]
Will work on it

**Comment by imduchuyyy** [comment]
> Will work on it

checkout #280

**Comment by drortirosh** [comment]
nice, but I don't think it should be in SimpleAccount - maybe in a separate sample contract.
