### ISSUE TITLE
Add "value" parameter to `SimpleAccount.executeBatch`

### ISSUE THREAD

**Issue by kaiix** [eth-infinitism/account-abstraction#275]
Why doesn't the `SimpleAccount.executeBatch` method take a `value` parameter like normal `execute`? For example, encode multiple transfer in `executeBatch` is better then execute a multicall.

[execute](https://github.com/eth-infinitism/account-abstraction/blob/75f02457e71bcb4a63e5347589b75fa4da5c9964/contracts/samples/SimpleAccount.sol#LL67C1-L68C1):
`function execute(address dest, uint256 value, bytes calldata func)`

[executeBatch](https://github.com/eth-infinitism/account-abstraction/blob/75f02457e71bcb4a63e5347589b75fa4da5c9964/contracts/samples/SimpleAccount.sol#L75):
`function executeBatch(address[] calldata dest, bytes[] calldata func)`

revised `executeBatch` with value:
`function executeBatch(address[] calldata dest, uint256[] value, bytes[] calldata func)`

it was originally introduced for `DepositPaymaster`, I think it can have broader use after the modification.

**Comment by drortirosh** [comment]
replied in #281

**Comment by hongqn** [comment]
> replied in #281

Excuse me, but I didn't see a response in #281, yet?
