### ISSUE TITLE
Do you have the EntryPoint contract address deployed on BSC?

### ISSUE THREAD

**Issue by amazingMan2017** [eth-infinitism/account-abstraction#285]
I see that you have deployed an official EntryPoint contract address on Polygon at 0x0576a174d229e3cfa37253523e645a78a0c91b57. Could you please tell me if you also have the official EntryPoint contract address deployed on the BSC network?

**Comment by eloi010** [comment]
The EntryPoint at address `0x0576a174D229E3cFA37253523E645A78A0C91B57` is an old version. You can see on Blockscan that it was deployed in multiple EVM chains: https://blockscan.com/address/0x0576a174d229e3cfa37253523e645a78a0c91b57, but BSC mainnet is not one of them. That version is available on Testnet BSC though.

Luckily, the latest version of the EntryPoint as of May 2023 is 0.6.0, and it can be found at address `0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789` on [BSC mainnet](https://bscscan.com/address/0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789) and [other chains](https://blockscan.com/address/0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789). More information about the upgrade: https://mirror.xyz/erc4337official.eth/cSdZl9X-Hce71l_FzjVKQ5eN398ial7QmkDExmIIOQk.
