### ISSUE TITLE
Handle 'postOp' revert with <32 bytes size

### ISSUE THREAD

**Issue by forshtat** [eth-infinitism/account-abstraction#289]
As mentioned here: 

https://github.com/pimlicolabs/erc20-paymaster-contracts/pull/2#issuecomment-1522235565

**Comment by drortirosh** [comment]
Right.
It is an inconsistency of `hardhat` with the spec:
hardhat reverts on returndatacopy if there is no return data, but geth silently returns..
Yes, we SHOULD check the `returndatasize` first...
