### ISSUE TITLE
Issues with Entrypoint execute and refund gas calculations

### ISSUE THREAD

**Issue by lakshyakumar** [eth-infinitism/account-abstraction#290]
The sample smart contracts should refund the exact or more amount of gas spent by the bundler, but in the execution I can see there are less gas refunded to the bundler, That can cause some miscalculations i deposits and spending by the entrypoint for example the transaction gas and the fee refunded to the bundler is different in the below transaction, 
<img width="1075" alt="image" src="https://github.com/eth-infinitism/account-abstraction/assets/56861637/96770e90-2662-410c-aca8-4240bb2460a3">

**Comment by wildmolasses** [comment]
did you already have some deposit on the entrypoint? what is the cause of this miscalculation?

**Comment by drortirosh** [comment]
exactly. probably your contract had a deposit from a previous transaction.
if you still think there is an issue, please provide an actual transaction on etherscan.
