### ISSUE TITLE
During the initCode the _createSenderIfNeeded in EntryPoint is failing

### ISSUE THREAD

**Issue by kushagra2jindal** [eth-infinitism/account-abstraction#314]
My txn is failing because of the line inside EntryPoint contract - `if (sender1 != sender) revert FailedOp(opIndex, "AA14 initCode must return sender");` . I am creating the initCode as follows:- 

```
let params = web3.eth.abi.encodeParameters(
        ['address', 'uint256'],
        // ['0xd28488F3b9b3600E6e05cb624ae2219BFAc6721C', 0]
        ['new Wallet Address', 40766180530947807426575232533125n]
    );
    params = '0x5fbfb9cf' + params.slice(2);
    // console.log(params);

    const codeInit = hexConcat([
        simpleAppFactory,
        params
    ])
    console.log(codeInit);

```
UserOps.sender = 0xd82695811E3eC9523F5a2282816493346a156701

Query - In the entry point contract, the sender1 is the value 'ret' returned from the SenderCreater using mload, which is the value of the new smart contract deployed - SimpleAccount. Whereas sender is the value of EOA sent in UserOps!! How are these two values matching?

**Comment by dbadoy** [comment]
You must enter the address of the smart account you want to create in the UserOperation.sender.

**Comment by kushagra2jindal** [comment]
Thanks @dbadoy closing the issue.
