### ISSUE TITLE
[N11] IWallet doesn't strongly enforce required functionality

### ISSUE THREAD

**Issue by drortirosh** [eth-infinitism/account-abstraction#33]
The IWallet interface specifies a single validateUserOp function that must be implemented by the wallet developer. This function's docstring lists requirements that must be enforced by the implementation such as checking and incrementing the nonce and verifying that the function was called by the EntryPoint contract. The SimpleWallet sample contract contains all the necessary logic in its own validateUserOp implementation, but developers are not required to use this code and could make errors when attempting to refactor it into their own custom implementation.
To help developers create secure wallet implementations that follow the EIP specification, consider removing the IWallet interface and replacing it with an abstract "BaseWallet" contract that implements all of the mandated checks, but leaves the custom behavior such as validateSignature up to derived classes. The existing SimpleWallet contract would then be derived from BaseWallet.

**Comment by yoavw** [comment]
A BaseWallet would indeed be nice, similarly to BasePaymaster that we already added.  However, it still won't be able to enforce that the implementation is correct.  For example, we don't require *incrementing* the nonce, just using it to prevent replay.  We shouldn't enforce a specific scheme which might prevent some forms of batching.  E.g. a wallet that uses a 2D nonce scheme to allow parallelization, or even a wallet built for a specific use, where replay protection isn't needed at all.

Despite that, it's worth having a BaseWallet even just to enforce that certain functions are only called from EntryPoint, and to have a mandatory setEntryPoint method (which also must be called either by the wallet itself or by EntryPoint).  @drortirosh WDYT?

**Comment by drortirosh** [comment]
fixed by #82
