### ISSUE TITLE
Add new test cases

### ISSUE THREAD

**Issue by mirrorzk** [eth-infinitism/account-abstraction#340]
I am currently attempting to add more test cases to this testing repository. Does anyone have any needs or suggestions?
https://github.com/eth-infinitism/account-abstraction/tree/develop/test

**Comment by shahafn** [comment]
Hi @Mirror-Tang , the tests in this repo, while important, only cover the contracts themselves, and not the full functionality specified in the eip. It'd be great if you could help us add tests to https://github.com/eth-infinitism/bundler-spec-tests, a repo that's supposed to cover the bundler's specification.

**Comment by mirrorzk** [comment]
> Hi @Mirror-Tang , the tests in this repo, while important, only cover the contracts themselves, and not the full functionality specified in the eip. It'd be great if you could help us add tests to https://github.com/eth-infinitism/bundler-spec-tests, a repo that's supposed to cover the bundler's specification.

Thank you for your response, I will try to do so immediately. I also need some advice, how can I get in touch with you?
