### ISSUE TITLE
For newer version of @openzeppelin/contracts@^5.0.0 ERC777 has been removed.

### ISSUE THREAD

**Issue by adityabhattad2021** [eth-infinitism/account-abstraction#354]
In the most recent release of the @openzeppelin/contracts library, the ERC777-related contracts have been removed. As a consequence,  the IERC777Recipient interface used in the @account-abstraction/contracts/samples/callback/TokenCallbackHandler.sol file, triggers an error.

For additional context and reference, here are the relevant screenshots and links

Openzeppelin change log. 

![Screenshot 2023-10-11 121522](https://github.com/eth-infinitism/account-abstraction/assets/93488388/f06f3b67-83b5-45ac-b04d-ddc779e073ad)

![Screenshot 2023-10-11 121451](https://github.com/eth-infinitism/account-abstraction/assets/93488388/a83f2a88-cd24-4a18-9366-1a5be4f0188e)

@account-abstraction/contracts/samples/callback/TokenCallbackHandler.sol 
![Screenshot 2023-10-11 121617](https://github.com/eth-infinitism/account-abstraction/assets/93488388/0d875160-b0ab-4687-a5c3-9f6796a4c2bd)

.

**Comment by drortirosh** [comment]
removing as part of upgrade to OZ 5.0
