### ISSUE TITLE
Remove free functions from `Helpers.sol` as it breaks compilation

### ISSUE THREAD

**Issue by vladikopl01** [eth-infinitism/account-abstraction#367]
I request to change `Helpers.sol` file to have a library in it with already existing functions because using free functions leads to compilation errors using with `@openzeppelin/hardhat-upgrades` libs.

More description about that issue is here: https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/917

**Comment by drortirosh** [comment]
From the attached issue, it seems to be a bug in the openzeppelin-upgrades rewrite mechanism, not anything related to this package.

**Comment by vladikopl01** [comment]
> From the attached issue, it seems to be a bug in the openzeppelin-upgrades rewrite mechanism, not anything related to this package.

Anyway, I think using free functions is not a good option based on style guides and basic concepts of good-written smart-contracts. It is better to use libraries for such cases.
