### ISSUE TITLE
Checking verificationGasLimit is not necessary in paymaster validateUserOp() 

### ISSUE THREAD

**Issue by livingrockrises** [eth-infinitism/account-abstraction#376]
https://github.com/eth-infinitism/account-abstraction/blob/develop/contracts/samples/LegacyTokenPaymaster.sol#L78

referring to this line. If VGL is sent low it would fail on simulation by bundler and would not need to cause on-chain invalidation sooner.

**Comment by shahafn** [comment]
We're going to remove this paymaster as it's no longer relevant

**Comment by livingrockrises** [comment]
> We're going to remove this paymaster as it's no longer relevant

yup acknowledged but regardless can we discuss if this check should be necessary.

**Comment by drortirosh** [comment]
note that paymasters may still check such values, since a paymaster (contract) can't trust an off-chain bundler.
Actually, anyone can issue a call to handleOps() with arbitrary gasLimit values.
