### ISSUE TITLE
Unable to send UserOperation on immutable zkEVM chain testnet

### ISSUE THREAD

**Issue by kishantrikon** [eth-infinitism/account-abstraction#386]
I am trying to deploy & run Account abstraction on Immutable zkEVM chain and I'm encountering an issue while attempting to send a user operation on Immutable Testnet using the eth-infinitism repo & Bundler repo.
I have deployed the Entrypoint smart contract, SimpleAccount Factory and Paymaster smart contract on the Immutable testnet and initialised paymaster also by depositing some funds. Also, run the bundler on my local machine by changing necessary configuration regarding RPC and Entrypoint Smart contract. I am sending simple useroperation on immutable chain but it gives me below error: 
**"message":"Cannot read properties of undefined (reading 'paymaster')"**

I have tried on polygon testnet by changing necessary details & it's working fine with the own bundler and paymaster, but I am getting above error while working with Immutable zkEVM testnet and also facing same issue wit Telos testnet.

**Comment by drortirosh** [comment]
it is very hard to diagnose it this way.
do you have a reference sample we can look at?
