### ISSUE TITLE
unable to  send userOperation to the bundlers

### ISSUE THREAD

**Issue by Shivamycodee** [eth-infinitism/account-abstraction#387]
hi i'm trying to implement the account abstraction myself:

for that i have created and deployed required contracts (mumbai network):

SimpleAccountFactory:  0xA9F87c30Ff0cc0b7D481b62297e036C628526059
my smart contract account (SCA deployed):  0x3E2341F136005F88323dDdF5BA025c0b9Bb41feF

I have deposited matic to my SCA and some ERC20 token, now i'm trying to call a simple approve function , and the PRC URL i'm using from api.stackup.sh is working fine cuz the error i get is not about RPC but the ProviderError: execution reverted.

here is my userOperation that i'm sending to the bundler.

```
opObject :  {
  sender: '0x3E2341F136005F88323dDdF5BA025c0b9Bb41feF',
  nonce: 120,
  initCode: '0x',
  callData: '0x095ea7b300000000000000000000000031a92fca50f511db28b57185ed6ae12f565f27620000000000000000000000000000000000000000000000056bc75e2d63100000',
  callGasLimit: 78051n,
  verificationGasLimit: 879620n,
  preVerificationGas: 735880n,
  maxFeePerGas: 24783214590n,
  maxPriorityFeePerGas: 16522143060n,
  paymasterAndData: '0x',
  signature: '0xb29b988d8629b6......44394ca592cd81b'
}
```

I'm sending this userOperation to the bundler with a zero address as benificiary cuz i'm ready to pay the transaction fee through SCA.

I have tried everything but couldn't solve the issue.

**Comment by drortirosh** [comment]
> I'm sending this userOperation to the bundler with a zero address as benificiary cuz i'm ready to pay the transaction fee through SCA.

you should set the beneficiary as your address. zero is not allowed: [see here](https://github.com/eth-infinitism/account-abstraction/blob/develop/contracts/core/EntryPoint.sol#L60)

**Comment by Shivamycodee** [comment]
Hello @drortirosh , I've encountered a small issue while sending my `userOperation` using `eth_sendUserOperation`. Could you kindly take a moment to review it?

[ethereum.stackexchange.com](https://ethereum.stackexchange.com/questions/158416/troubleshooting-a-failing-transaction-in-ethereum-account-abstraction)
