### ISSUE TITLE
detailed ErrorMessage while reverting for AA91 during compensate() call

### ISSUE THREAD

**Issue by kanthgithub** [eth-infinitism/account-abstraction#409]
## Description
AA91 error is thrown when the compensate function fails to transfer the collected fees to the beneficiary
however, the value of the amount is not part of error message,

### Proposal-1
It would be nice to append the `amount` to the error message 
https://github.com/eth-infinitism/account-abstraction/blob/develop/contracts/core/EntryPoint.sol#L70

it comes at some addl gas cost but helps to identify the amount for which transfer has failed

### Proposal-2
We can convert this to a revert Error like how its being done for other Errors like FailedOp (AA95)
we can keep 

```
error FailedFeesCompensation(uint256 collectedFees, address beneficiaryAddress, string reason)
```

**Comment by drortirosh** [comment]
What is the benefit of handling it?
This is not a user-facing API. it is a bundler-specific API, and the receiving address is bundler-specific beneficiary, not some end-user account.
