### ISSUE TITLE
Is the tokenPaymaster over prefund?

### ISSUE THREAD

**Issue by doublespending** [eth-infinitism/account-abstraction#435]
In my mind, `requiredPreFund` from EntryPoint includes fund for postOp.
* https://github.com/eth-infinitism/account-abstraction/blob/0766b38ad165bfaecdd60b46cf72db93aa6793a9/contracts/core/EntryPoint.sol#L511-L515
* https://github.com/eth-infinitism/account-abstraction/blob/0766b38ad165bfaecdd60b46cf72db93aa6793a9/contracts/core/EntryPoint.sol#L378-L390

Why should we add additional `(refundPostopCost * maxFeePerGas)` above `requiredPreFund` here?
* https://github.com/eth-infinitism/account-abstraction/blob/0766b38ad165bfaecdd60b46cf72db93aa6793a9/contracts/samples/TokenPaymaster.sol#L132

**Comment by drortirosh** [comment]
the calculation was updated with v0.7 with the new paymaserVerificationGasLimit

**Comment by 0xrubes** [comment]
Sorry for commenting on an old issue, but I'm not following the explanation @drortirosh. The `TokenPaymaster` moved to the samples repo now, but commenting here made more sense to me. The v0.7 release of the `TokenPaymaster` contract  is still used as a reference for many V0.7 paymaster implementations. It is relevant in a security review we're conducting right now.

`tokenPaymasterConfig.refundPostopCost` seems to include some minor unaccounted EP overhead as well as the estimated postOp gas costs. As @doublespending pointed out, the `requiredPreFund` also includes the `postOpGasLimit`. `postOpGasLimit` is asserted to be an upper bound to `refundPostopCost`.  Therefore, I think, this calculation is

The variable seems to try to do two things at once: 1) contain only the unaccounted gas of EntryPoint overhead and 2) contain unaccounted gas of EntryPoint overhead + estimated total costs of postOp call. 

1) seems to be used in the line @doublespending highlighted (resulting in postOpGasLimit + estimated postOpGas  essentially double-charging postOp-flow)
2) seems to be used [here](https://github.com/eth-infinitism/account-abstraction/blob/7af70c8993a6f42973f520ae0752386a5032abe7/contracts/samples/TokenPaymaster.sol#L171), correctly including unaccounted EP gas + estimated postOp costs.

While this only results in slightly overcharging the paymaster, it would be great to get some insights from you on this :)
