### ISSUE TITLE
AA51 will revert the entire bundle

### ISSUE THREAD

**Issue by xinweb4** [eth-infinitism/account-abstraction#442]
Once AA51 occurs, even if it is captured, it will still be thrown again, resulting in **the entire bundle being reverted.**

#### First revert
![telegram-cloud-photo-size-5-6195039426384608268-y](https://github.com/eth-infinitism/account-abstraction/assets/20449332/0f50715e-e5d2-4f06-9dcf-0f92ea083aeb)

#### First catch
![telegram-cloud-photo-size-5-6195039426384608269-y](https://github.com/eth-infinitism/account-abstraction/assets/20449332/d808ab76-a187-4242-aa24-ca8d8950f10f)

#### Retry
![telegram-cloud-photo-size-5-6195039426384608270-y](https://github.com/eth-infinitism/account-abstraction/assets/20449332/56f74d05-b9aa-4a28-a52f-2559bf770381)

#### Second revert
![telegram-cloud-photo-size-5-6195039426384608271-y](https://github.com/eth-infinitism/account-abstraction/assets/20449332/db0e5183-7ed8-4a75-ac22-a5f7e35160ad)

#### Revert the entire bundle
![telegram-cloud-photo-size-5-6195039426384608272-y](https://github.com/eth-infinitism/account-abstraction/assets/20449332/8526bdf6-d7db-4b7c-a1e3-fcb64ffb4a89)

### Example in 0.6
https://dashboard.tenderly.co/tx/polygon/0x73b7bf023e8c7b54a374e77bd62702eacce6877c118fef06dd5a6d4cd15954e9

**Comment by drortirosh** [comment]
this issue was addressed in the security audit.
was fixed for ver0.7, and a mitigation was suggested and deployed in bundlers of v0.6
