### ISSUE TITLE
[N23] Unused parameter in validatePaymasterUserOp methods

### ISSUE THREAD

**Issue by drortirosh** [eth-infinitism/account-abstraction#45]
The validatePaymasterUserOp function in the IPaymaster interface takes a requestId parameter which can be calculated by calling the getRequestId function of EntryPoint. None of the paymaster sample contracts (TokenPaymaster, VerifyingPaymaster, DepositPaymaster) use this variable in their implementations of validatePaymasterUserOp, making it unclear as to why it is being included in the interface.
                                   
 Consider providing a sample paymaster contract that demonstrates the use of the requestId parameter for validation.

**Comment by drortirosh** [comment]
calculation of the requestId can be potentially expensive (e.g. when deploying a new contract), so we don't want to force a paymaster to re-calculate it. 
its true that current examples of paymasters don't need it (VerifyingPaymaster does need an equivalent hash - but one that doesn't cover the paymasterData, so it has to calculate a different one)

**Comment by yoavw** [comment]
As @drortirosh explained, this value is potentially useful for paymasters, and already calculated by EntryPoint for other uses. So it's best to propagate it to paymasters even if some of them won't use it.
