### ISSUE TITLE
build: `@typechain/hardhat` is deprecated

### ISSUE THREAD

**Issue by pegahcarter** [eth-infinitism/account-abstraction#462]
Typechain is considered [legacy](https://github.com/dethcrypto/TypeChain?tab=readme-ov-file#soft-deprecation-notice) and is no longer actively supported.  I suggest migrating the dependency to [viem](https://github.com/wevm/viem).

https://github.com/eth-infinitism/account-abstraction/blob/7af70c8993a6f42973f520ae0752386a5032abe7/package.json#L58

**Comment by drortirosh** [comment]
Basically, you're right.
But this is a test code. we do plan to rewrite the tests using viem (or forge), but we currently don't have the capacity.
