### ISSUE TITLE
getReturnData function in Exec.sol is unable to retrieve result from delegatecall

### ISSUE THREAD

**Issue by 2klonghua** [eth-infinitism/account-abstraction#467]
After using Exec.delegateCall(...), it seems that I cannot rely on Exec.getReturnData(..) to retrieve the delegate call result.

I have tested this behaviour on Remix:

Steps:
1. Use this 2 contract: (uploaded as .txt since Git does not support .sol file, please replace to .sol)
[DelegateTarget.txt](https://github.com/eth-infinitism/account-abstraction/files/14863896/DelegateTarget.txt)
[Caller.txt](https://github.com/eth-infinitism/account-abstraction/files/14863894/Caller.txt)

2. Call the performDelegateCall function on Caller.sol by passing DelegateTarget.sol address, and observe that the returndatasize is always 0 in getReturnData function.

Observation:
1. I notice that if I call the returndatasize() in assembly block within the performDelegateCall function, the value is correct. I suspect that the returndatasize() value is only preserved before another function call (not necessary to be within the assembly block) is made. Can anyone clarify this?

**Comment by drortirosh** [comment]
getReturnData is allowed to be called only directly after call/delegatecall.
You're using "console.log" which by itself is a CALL, which clears the return data.
simply call "result" before calling the console.log....
(I know, its confusing. I hit the same problem once myself...)
