### ISSUE TITLE
package.json in main branch in using openzeppelin v4 which has breaking changes in openzeppelin v5

### ISSUE THREAD

**Issue by ANNMAINAWANGARI** [eth-infinitism/account-abstraction#471]
@openzeppelin/contracts/token/ERC777/IERC777Recipient.sol is not exported in openzeppelin v5 which is being used in account-abstraction/contracts/samples/callback/TokenCallbackHandler.sol. This does not work in openzeppelin v5. npm i @account-abstraction/contracts uses openzeppelin v4. Suggest upgrading in the main branch.

**Comment by drortirosh** [comment]
the old (v0.6) version of the package (on branch releases/v0.6) did use openzeppelin v4, but the latest version (v0.7, on branch develop and master) uses openzeppelin v5, and removed any reference to the deprecated ERC777

**Comment by ANNMAINAWANGARI** [comment]
How can I use v0.7,I guess one can fork but is there a way to use it via npm install @account-abstraction/contracts?

**Comment by drortirosh** [comment]
`npm install @account-abstraction/contracts`. the v0.7 is the published version.

**Comment by ANNMAINAWANGARI** [comment]
Great thanks
