### ISSUE TITLE
Is version 0.7 already deployed?

### ISSUE THREAD

**Issue by sdelvalle57** [eth-infinitism/account-abstraction#474]
Im using the bundler and `@account-abstraction/contracts`, at version 0.7

But when I try to `npm install @account-abstraction/sdk@0.7.0 && npm install @account-abstraction/utils@0.7.0` Im getting `No matching version found for @account-abstraction/utils@^0.7.0.` and `No matching version found for @account-abstraction/sdk@^0.7.0.`

I see the bundler uses these versions, why I cant get to install them in my project?

**Comment by marcelomorgado** [comment]
I think so, I was able to find the address `0x0000000071727De22E5E9d8BAf0edAc6f37da032` from [Kernel wallet repo](https://github.com/zerodevapp/kernel/blob/dev/src/sdk/TestBase/erc4337Util.sol#L13) but there isn't any reference for the address on this repo. I guess they missed to upgrade the `deployments` folder.

**Comment by SunZhiC** [comment]
https://www.npmjs.com/package/@account-abstraction/sdk?activeTab=versions the latest version in npm is 0.6

**Comment by drortirosh** [comment]
the latest published npm version is currently 0.7: https://www.npmjs.com/package/@account-abstraction/contracts
