### ISSUE TITLE
Initial UserOperation Fails due to initCode in Account Abstraction v0.7

### ISSUE THREAD

**Issue by kishantrikon** [eth-infinitism/account-abstraction#490]
### Description:
I am encountering an issue when deploying a smart account wallet using the initCode functionality in the initial UserOperation. Despite following standard practices for generating initCode, I consistently receive errors. Only getting errors with Account Abstraction version v0.7 Previous versions worked without this issue.

**Context**:

To run the Useroperation I'm Manually deploying the smart account wallet using the SimpleAccountFactory & after that subsequent UserOperations function seamlessly, including paymaster functionalities.

**Issue**:
The problem persists solely with the first UserOperation that includes the initCode.

**Errors Encountered:**
From Bundler: "AA20 account not deployed"
Direct Stimulation on EntryPoint Contract: "AA13 initCode failed or OOG" error.

**InitCode Generation Process:**
`const initCode = ethers.utils.hexConcat([
    Config.SIMPLE_ACCOUNT_FACTORY_ADDRESS,
    contract.newsimpleAccountFactory.interface.encodeFunctionData("createAccount", [owner.address, 0])
]);
`

The initial UserOperation with initCode should deploy the smart account wallet and allow subsequent UserOperations to function correctly without manual intervention.

I am looking for guidance to resolve this issue. Any help or pointers would be immensely helpful.

**Comment by yamel22s** [comment]
Nckljgh

**Comment by yamel22s** [comment]
Jghoohggffjko

**Comment by yamel22s** [comment]
Vcjoooo

**Comment by drortirosh** [comment]
It is a little tricky to debug deployment failure.
- try call the factory directly, to see the calldata indeed creates the account
- make sure the verificationGasLimit is high enough, to cover deployment (and validation)
- you can try to use an SDK to create account, instead of directly creating UserOperations.
- If you have further errors, you can ask on the discord channel: https://discord.gg/PVt4dn7zcQ
