### ISSUE TITLE
UserOpEvent.gasActualUsed is more than tx.gasUsed

### ISSUE THREAD

**Issue by GDdark** [eth-infinitism/account-abstraction#495]
https://sepolia.etherscan.io/tx/0xf491000da69c715a72ae243f6d558f63252f34b419f619bd6e7775978fa5935b

![image](https://github.com/user-attachments/assets/b7bfb54b-fd1b-4141-992b-f45103fa4621)
![image](https://github.com/user-attachments/assets/05e7fb11-857f-4134-ae95-86e7f93b4abd)

Typically, tx.gasUsed should be greater than UserOpEvent.gasActualGas.

What causes this situation?

**Comment by drortirosh** [comment]
actualGasUsed is the amount of the account paid - what was calculated during its execution, and also the "self-declared" preVerificationGas (which can't be calculated on-chain)
In this case, the sender of this transaction put 100000 for preVerificationGas, and it was added to the actualGasUsed calculations. Obviously, this is more than that actual cost (which includes 21000 + calldata cost, which is usually few 1000s)
